// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Club        string
	Clubplayer  string
	Competition string
	Game        string
	Player      string
	Playerteam  string
	Season      string
	Team        string
}{
	Club:        "club",
	Clubplayer:  "clubplayer",
	Competition: "competition",
	Game:        "game",
	Player:      "player",
	Playerteam:  "playerteam",
	Season:      "season",
	Team:        "team",
}
