// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testGames(t *testing.T) {
	t.Parallel()

	query := Games()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testGamesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Game{}
	if err = randomize.Struct(seed, o, gameDBTypes, true, gameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Game struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Games().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testGamesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Game{}
	if err = randomize.Struct(seed, o, gameDBTypes, true, gameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Game struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Games().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Games().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testGamesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Game{}
	if err = randomize.Struct(seed, o, gameDBTypes, true, gameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Game struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := GameSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Games().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testGamesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Game{}
	if err = randomize.Struct(seed, o, gameDBTypes, true, gameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Game struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := GameExists(ctx, tx, o.GameID)
	if err != nil {
		t.Errorf("Unable to check if Game exists: %s", err)
	}
	if !e {
		t.Errorf("Expected GameExists to return true, but got false.")
	}
}

func testGamesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Game{}
	if err = randomize.Struct(seed, o, gameDBTypes, true, gameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Game struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	gameFound, err := FindGame(ctx, tx, o.GameID)
	if err != nil {
		t.Error(err)
	}

	if gameFound == nil {
		t.Error("want a record, got nil")
	}
}

func testGamesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Game{}
	if err = randomize.Struct(seed, o, gameDBTypes, true, gameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Game struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Games().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testGamesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Game{}
	if err = randomize.Struct(seed, o, gameDBTypes, true, gameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Game struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Games().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testGamesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	gameOne := &Game{}
	gameTwo := &Game{}
	if err = randomize.Struct(seed, gameOne, gameDBTypes, false, gameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Game struct: %s", err)
	}
	if err = randomize.Struct(seed, gameTwo, gameDBTypes, false, gameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Game struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = gameOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = gameTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Games().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testGamesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	gameOne := &Game{}
	gameTwo := &Game{}
	if err = randomize.Struct(seed, gameOne, gameDBTypes, false, gameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Game struct: %s", err)
	}
	if err = randomize.Struct(seed, gameTwo, gameDBTypes, false, gameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Game struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = gameOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = gameTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Games().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func gameBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Game) error {
	*o = Game{}
	return nil
}

func gameAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Game) error {
	*o = Game{}
	return nil
}

func gameAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Game) error {
	*o = Game{}
	return nil
}

func gameBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Game) error {
	*o = Game{}
	return nil
}

func gameAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Game) error {
	*o = Game{}
	return nil
}

func gameBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Game) error {
	*o = Game{}
	return nil
}

func gameAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Game) error {
	*o = Game{}
	return nil
}

func gameBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Game) error {
	*o = Game{}
	return nil
}

func gameAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Game) error {
	*o = Game{}
	return nil
}

func testGamesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Game{}
	o := &Game{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, gameDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Game object: %s", err)
	}

	AddGameHook(boil.BeforeInsertHook, gameBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	gameBeforeInsertHooks = []GameHook{}

	AddGameHook(boil.AfterInsertHook, gameAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	gameAfterInsertHooks = []GameHook{}

	AddGameHook(boil.AfterSelectHook, gameAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	gameAfterSelectHooks = []GameHook{}

	AddGameHook(boil.BeforeUpdateHook, gameBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	gameBeforeUpdateHooks = []GameHook{}

	AddGameHook(boil.AfterUpdateHook, gameAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	gameAfterUpdateHooks = []GameHook{}

	AddGameHook(boil.BeforeDeleteHook, gameBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	gameBeforeDeleteHooks = []GameHook{}

	AddGameHook(boil.AfterDeleteHook, gameAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	gameAfterDeleteHooks = []GameHook{}

	AddGameHook(boil.BeforeUpsertHook, gameBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	gameBeforeUpsertHooks = []GameHook{}

	AddGameHook(boil.AfterUpsertHook, gameAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	gameAfterUpsertHooks = []GameHook{}
}

func testGamesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Game{}
	if err = randomize.Struct(seed, o, gameDBTypes, true, gameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Game struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Games().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testGamesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Game{}
	if err = randomize.Struct(seed, o, gameDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Game struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(gameColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Games().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testGameToManyGameIDPlayerteams(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Game
	var b, c Playerteam

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, gameDBTypes, true, gameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Game struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, playerteamDBTypes, false, playerteamColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, playerteamDBTypes, false, playerteamColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.GameID = a.GameID
	c.GameID = a.GameID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.GameIDPlayerteams().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.GameID == b.GameID {
			bFound = true
		}
		if v.GameID == c.GameID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := GameSlice{&a}
	if err = a.L.LoadGameIDPlayerteams(ctx, tx, false, (*[]*Game)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.GameIDPlayerteams); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.GameIDPlayerteams = nil
	if err = a.L.LoadGameIDPlayerteams(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.GameIDPlayerteams); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testGameToManyAddOpGameIDPlayerteams(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Game
	var b, c, d, e Playerteam

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, gameDBTypes, false, strmangle.SetComplement(gamePrimaryKeyColumns, gameColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Playerteam{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, playerteamDBTypes, false, strmangle.SetComplement(playerteamPrimaryKeyColumns, playerteamColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*Playerteam{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddGameIDPlayerteams(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.GameID != first.GameID {
			t.Error("foreign key was wrong value", a.GameID, first.GameID)
		}
		if a.GameID != second.GameID {
			t.Error("foreign key was wrong value", a.GameID, second.GameID)
		}

		if first.R.GameID != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.GameID != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.GameIDPlayerteams[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.GameIDPlayerteams[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.GameIDPlayerteams().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}
func testGameToOneSeasonUsingSeasonID(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Game
	var foreign Season

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, gameDBTypes, false, gameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Game struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, seasonDBTypes, false, seasonColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Season struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.SeasonID = foreign.SeasonID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.SeasonID().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.SeasonID != foreign.SeasonID {
		t.Errorf("want: %v, got %v", foreign.SeasonID, check.SeasonID)
	}

	slice := GameSlice{&local}
	if err = local.L.LoadSeasonID(ctx, tx, false, (*[]*Game)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.SeasonID == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.SeasonID = nil
	if err = local.L.LoadSeasonID(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.SeasonID == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testGameToOneTeamUsingTeam1(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Game
	var foreign Team

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, gameDBTypes, false, gameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Game struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, teamDBTypes, false, teamColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Team struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.Team1 = foreign.TeamID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Team1().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.TeamID != foreign.TeamID {
		t.Errorf("want: %v, got %v", foreign.TeamID, check.TeamID)
	}

	slice := GameSlice{&local}
	if err = local.L.LoadTeam1(ctx, tx, false, (*[]*Game)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Team1 == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Team1 = nil
	if err = local.L.LoadTeam1(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Team1 == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testGameToOneTeamUsingTeam2(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Game
	var foreign Team

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, gameDBTypes, false, gameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Game struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, teamDBTypes, false, teamColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Team struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.Team2 = foreign.TeamID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Team2().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.TeamID != foreign.TeamID {
		t.Errorf("want: %v, got %v", foreign.TeamID, check.TeamID)
	}

	slice := GameSlice{&local}
	if err = local.L.LoadTeam2(ctx, tx, false, (*[]*Game)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Team2 == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Team2 = nil
	if err = local.L.LoadTeam2(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Team2 == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testGameToOneSetOpSeasonUsingSeasonID(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Game
	var b, c Season

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, gameDBTypes, false, strmangle.SetComplement(gamePrimaryKeyColumns, gameColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, seasonDBTypes, false, strmangle.SetComplement(seasonPrimaryKeyColumns, seasonColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, seasonDBTypes, false, strmangle.SetComplement(seasonPrimaryKeyColumns, seasonColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Season{&b, &c} {
		err = a.SetSeasonID(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.SeasonID != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.SeasonIDGames[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.SeasonID != x.SeasonID {
			t.Error("foreign key was wrong value", a.SeasonID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.SeasonID))
		reflect.Indirect(reflect.ValueOf(&a.SeasonID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.SeasonID != x.SeasonID {
			t.Error("foreign key was wrong value", a.SeasonID, x.SeasonID)
		}
	}
}
func testGameToOneSetOpTeamUsingTeam1(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Game
	var b, c Team

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, gameDBTypes, false, strmangle.SetComplement(gamePrimaryKeyColumns, gameColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, teamDBTypes, false, strmangle.SetComplement(teamPrimaryKeyColumns, teamColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, teamDBTypes, false, strmangle.SetComplement(teamPrimaryKeyColumns, teamColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Team{&b, &c} {
		err = a.SetTeam1(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Team1 != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.Team1Games[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.Team1 != x.TeamID {
			t.Error("foreign key was wrong value", a.Team1)
		}

		zero := reflect.Zero(reflect.TypeOf(a.Team1))
		reflect.Indirect(reflect.ValueOf(&a.Team1)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.Team1 != x.TeamID {
			t.Error("foreign key was wrong value", a.Team1, x.TeamID)
		}
	}
}
func testGameToOneSetOpTeamUsingTeam2(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Game
	var b, c Team

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, gameDBTypes, false, strmangle.SetComplement(gamePrimaryKeyColumns, gameColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, teamDBTypes, false, strmangle.SetComplement(teamPrimaryKeyColumns, teamColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, teamDBTypes, false, strmangle.SetComplement(teamPrimaryKeyColumns, teamColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Team{&b, &c} {
		err = a.SetTeam2(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Team2 != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.Team2Games[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.Team2 != x.TeamID {
			t.Error("foreign key was wrong value", a.Team2)
		}

		zero := reflect.Zero(reflect.TypeOf(a.Team2))
		reflect.Indirect(reflect.ValueOf(&a.Team2)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.Team2 != x.TeamID {
			t.Error("foreign key was wrong value", a.Team2, x.TeamID)
		}
	}
}

func testGamesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Game{}
	if err = randomize.Struct(seed, o, gameDBTypes, true, gameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Game struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testGamesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Game{}
	if err = randomize.Struct(seed, o, gameDBTypes, true, gameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Game struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := GameSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testGamesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Game{}
	if err = randomize.Struct(seed, o, gameDBTypes, true, gameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Game struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Games().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	gameDBTypes = map[string]string{`GameID`: `int`, `Round`: `int`, `SeasonID`: `int`, `Team1`: `int`, `Team2`: `int`, `T1Score`: `int`, `T2Score`: `int`, `MatchDate`: `date`, `MatchTime`: `time`}
	_           = bytes.MinRead
)

func testGamesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(gamePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(gameAllColumns) == len(gamePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Game{}
	if err = randomize.Struct(seed, o, gameDBTypes, true, gameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Game struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Games().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, gameDBTypes, true, gamePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Game struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testGamesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(gameAllColumns) == len(gamePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Game{}
	if err = randomize.Struct(seed, o, gameDBTypes, true, gameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Game struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Games().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, gameDBTypes, true, gamePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Game struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(gameAllColumns, gamePrimaryKeyColumns) {
		fields = gameAllColumns
	} else {
		fields = strmangle.SetComplement(
			gameAllColumns,
			gamePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := GameSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testGamesUpsert(t *testing.T) {
	t.Parallel()

	if len(gameAllColumns) == len(gamePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLGameUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Game{}
	if err = randomize.Struct(seed, &o, gameDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Game struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Game: %s", err)
	}

	count, err := Games().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, gameDBTypes, false, gamePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Game struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Game: %s", err)
	}

	count, err = Games().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
