// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Clubs", testClubsUpsert)

	t.Run("Clubplayers", testClubplayersUpsert)

	t.Run("Competitions", testCompetitionsUpsert)

	t.Run("Games", testGamesUpsert)

	t.Run("Players", testPlayersUpsert)

	t.Run("Playerteams", testPlayerteamsUpsert)

	t.Run("Seasons", testSeasonsUpsert)

	t.Run("Teams", testTeamsUpsert)
}
